# version: '3'

# services:
#   app:
#     build:
#       context: .
#     ports:
#       - "9000:80"
#     volumes:
#       - .:/var/www/html
#     depends_on:
#       - db

#   db:
#     image: mysql:latest
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#       MYSQL_DATABASE: property_management_system
